version: "3"
# see: https://taskfile.dev/usage/

tasks:
  build:
    sources:
      - Sources/**/*.swift
    generates:
      - .build
    cmds:
      - swift build
  run:
    cmds:
      - swift run toy-swift
  fmt:
    shopt: [globstar]
    cmds:
      - swift-format format --in-place ./**/*.swift
